### ISSUE TITLE
Missing 3rd party module

### ISSUE THREAD

**Issue by ljonsson** [Kintyre/ksconf#48]
# The problem

When running ksconf where the splunk environment variables haven't been set properly it gives a rather unhelpful error message.

## Environment

ksconf 0.7.0  (Build 320)
Python: 2.7.14  (/opt/splunk/bin/python)
CentOS Linux release 7.6.1810 (Core)
Splunk app installed from tarball

## Details

When the splunk environment variables from `setSplunkEnv` have not been set, particularly `LD_LIBRARY_PATH`, ksconf fails with an error message about `Missing 3rd party module` for the `rest-publish` command, see below.  The obvious fix is to source `setSplunkEnv` in `.bash_profile` for example.

```
[splunk@mgmt01 ~]$ ksconf --version
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/opt/splunk/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/splunk/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/opt/splunk/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/splunk/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
 _                         __
| | _____  ___ ___  _ __  / _|
| |/ / __|/ __/ _ \| '_ \| |_
|   <\__ \ (_| (_) | | | |  _|
|_|\_\___/\___\___/|_| |_|_|

ksconf 0.7.0  (Build 320)
Python: 2.7.14  (/opt/splunk/bin/python)
Git SHA1 fbf699e3 committed on 2019-02-27
Installed at: /opt/splunk/etc/apps/ksconf/bin/lib/ksconf
Written by Lowell Alleman <lowell@kintyre.co>.
Copyright (c) 2019 Kintyre Solutions, Inc, all rights reserved.
Licensed under Apache Public License v2

    Commands:
      check           (stable)    OK
      combine         (beta)      OK
      diff            (stable)    OK
      filter          (alpha)     OK
      merge           (stable)    OK
      minimize        (beta)      OK
      promote         (beta)      OK
      rest-export     (beta)      OK
      rest-publish    (alpha)     Missing 3rd party module:  libssl.so.1.0.0: cannot open shared object file: No such file or directory
      snapshot        (alpha)     OK
      sort            (stable)    OK
      unarchive       (beta)      OK
```

## Steps To Reproduce Issue
```
[splunk@mgmt01 ~]$ unset LD_LIBRARY_PATH
[splunk@mgmt01 ~]$ ksconf --version
```

**Comment by lowell80** [comment]
Thanks for reporting this @ljonsson and for all the effort to track down the issue.  You are correct, in that whenever you're running the Python that ships with Splunk there are certain environmental variables that must be set correctly or there can be confusion between the OS-level libraries and what's provided by Splunk.

Primarily the variables that are most impacting are `PATH` (which most people know to look for), then there's `LD_LIBRARY_PATH`, and `PYTHONPATH` (which impacts python only, and tends to be overlooked)

The challenge here, in my experience, is that when doing Splunk admin tasks can require jumping back and forth between OS-level tools and Splunk tools.  For example, because Splunk's `setSplunkEnv` sets `PYTHONPATH` that means that any OS-level python tool (like `yum`, for example) can run into issues because it may now try to use the Python site-packages that ship with Splunk and NOT the ones that ship with the OS.  (Now, in reality `yum` is probably a bad example, because you often run that via `sudo`, which protects you by scrubbing environmental variables at launch.  But if Splunk is running as root (not ideal, but it happens), then you would experience this issue.)  The issue here is that Splunk is setting `PYTHONPATH` in the first place, instead of using `virtualenv`-like approach; in which case Python program can easily co-exist, running from completely different sets of packages and even python versions without issue.  But as soon as `PYTHONPATH` is set, this isn't possible anymore.  ;-)

Simmiliary, if you use `git` which often is used with `ksconf` then some of the libraries in `LD_LIBRARY_PATH` can cause conflicts.  Another similar conflict i've seen is with Centrify's libraries (but if forget the details on that one.)

So there are no great universal fixes to this.   I'm hopeful that when Splunk moves off of Python 2.7 (which is end-of-life in [soon](https://pythonclock.org/)) they'll find a *better* way to handle this stuff.

But for right now you have 3 options:

  1.  Source `setSplunkEnv` for all your interactive shells, as you pointed out and then deal with any OS-level negative interactions.  (Note that this will also enable splunk CLI completion, which I think is nice.)  Another option is to run `splunk envvars` and only import *some* of the variables that you really want.
  2. Run `splunk cmd ksconf` which will setup the environment (just as setSplunkEnv) does, but it does so ONLY for the context of a single `ksconf` execution.   So this option works well with shell `alias`, but it will likely be slightly slower at startup.
  3.  Custom launcher shell script that tweaks the environment and then does and launches `ksconf` as of module.  (`python -m ksconf`).

At the very least, this needs to be document better.

I'm very open to additional ideas or additional feedback.  I'd like to find, and document, the most likely to work solutions with minimal negative side-effects.  Or possibly a simple decision-tree in the docs that points people to the best solution for them.

Oh, one more limitation is that Splunk's App Inspect takes issue with changes certain environmental variables being set programmatically, so there are some limitations on what can be shipped and delivered via Splunk base.

**Comment by lowell80** [comment]
@ljonsson, Please give the v0.7.1 release a try and see if that helps.  Reopen if the environment check doesn't work of if you have further ideas on how to improve.

Thanks again for taking the time to file this bug report.
