### ISSUE TITLE
write banner only for merged files

### ISSUE THREAD

**Issue by SID800** [Kintyre/ksconf#64]
## Is your feature request related to a problem? Please describe.

It would be helpful if there was an option for ksconf combine, to only write the banner if the file has been modified (as in, merged with other files)

## Describe the solution you'd like

The goal is to use ksconf as part of package building. The combine option is very helpful when merging organization changes into the original source code from a vendor's addon.  However, even if there is nothing being merged from the original source code, ksconf combine will still write the banner into the target files.  
The purpose of the banner is to inform admins that the file has been built by ksconf... but that does not make sense if there was truly no modifications besides a file copy. Ideally, unmerged files should remain untouched and maintain the same file hash as the original. 

## How serious are you about this change?  [ For not-trivial changes ]

This is a nice to have feature.

**Comment by lowell80** [comment]
The purpose of the banner is to discourage Splunk admins from editing auto-generated files.  If you're building an app or directory for consumption by a local Splunk instance, then it's quite helpful to let the admin know NOT to edit auto generated files, as they are much more likely to be overwritten the next time `ksconf combine` runs.  In such a use case, it doesn't matter if the target file was sourced from a single file, or the result of merging a dozen files; the point of the banner is to say "Hey you!  Don't edit *THIS* file, go find the source file and edit that".  (Most often the source files are housed within a version control system, but the target files generated by combine are not.)

For your use case, where ksconf is being used to build an app that will be packaged and shipped off somewhere else, I think the right answer is to fully disable the banner as it serves no purpose in that use case.  If anything, I suspect the banner would be confusing at that point.  Though, you could use the banner to drop in a build number of version string if desirable, which is why you you can set it, rather than just turn it on or off.

Note that the output files are hash stable as long as as none of the input files change.  (Although EOL between Windows/Nix should be factored in).  But in a typical deployment server scenario, for example, if the input files are changed, then the target isn't updated, and therefore the app won't' be redeployed by Splunk.

I can see the desire to allow unchanged files to pass-through in certain circumstances, such as app building.  But that's not currently implemented.  Pull request welcome.
