### ISSUE TITLE
enable installation in airgapped environments

### ISSUE THREAD

**Issue by tiberiustribun** [Kintyre/ksconf#67]
I am trying to setup ksconf as pre-commit hook in an airgapped environment. I cloned ksconf-master into a local gitlab server so that pre-commit can build the environment for ksconf hooks in my splunk repo. Sadly there are requirements like entrypoints.py that can not be resolved b/c https://pypi.org/simple/entrypoints is not reachable. 

I propose adding a new script to download all requirements for ksconf into the repo on an internet-connected machine so that  this repo can be transferred to the git server serving the airgapped machines. Basically similar to the 'make_splunk_app' script, only that the target is a standalone git repo instead of a splunk app. 

An alternative could be to include all external requirements in the ksconf master repo to begin with like with the splunk app build.

**Comment by lowell80** [comment]
I've used ksconf in an air gapped environment a few times before and it can be painful; but much of that is the nature of isolation and design assumptions made in of pre-commit.  For many ksconf use cases, the simple workaround is just using the Splunk app version of ksconf (as it includes all libraries).  Now that doesn't work for your `pre-commit` use cases, but I wanted to a least point out the most simple solution that should work for many.

I've toyed with the idea of including entrypoints.  Technically, it's not "required" as there is fallback code, but when installing with `pip`, and even more so with `pre-commit` there's no way to skip it. 
 But even if I inline that library, I think you'll find that other libraries (lxml, and possibly python-sdk) may also be required for the pre-commit use-case; and there's no way I'm embedding those in this repo; especially since lxml has platform-specific dependencies.  Frankly, all of this is quite the pain, it certainly seems like there should be an easier solution, but all of the half-dozen alternatives I've tried have equally painful corner cases.   (If you're a packaging guru, I'd welcome any assistance!)

So with all that background out of the way, here are some tricks I've used, and this should work fine no matter how many python packages are required.  (This does assume that you download packages on the same platform and python version as is running on your air gapped machine.)

1. Use offline install trick to pre-download PIP packages: 

        python2.7 -m pip download -d ksconf-packages kintyre-splunk-conf

2.  Now the trick is to convert the `--no-index --find-links=ksconf-packages` portion of the `pip install` command to something that can be passed to `pip`, even though it's actually being called by `pre-commit` and therefore you can't explicitly sent in arbitrary arguments.  Fortunately, these settings can also be set via environmental variables.  So run something like this:

        export PIP_FIND_LINKS=file:///tmp/downloads/ksconf-packages
        PIP_NO_INDEX=1 PYTHONPATH="" pre-commit install --install-hooks

  Note that for `PIP_FIND_LINKS` to be honored, a recent version of `pip` may be required.   The OS default python may be too old, for example.  I have some other notes about how to upgrade pip on the same advanced install doc.

Offline installation is further discussed in the docs here:
https://ksconf.readthedocs.io/en/latest/install_advanced.html#offline-installation-steps.  This isn't pre-commit specific, but it may give you some ideas.

If none of that works, a few other options are documented here in my conversation with the `pre-commit` folks the first time I tried to make this setup work:   https://github.com/pre-commit/pre-commit/issues/824.  The big takeaway there is that you can essentially clone portions of the `.pre-commit` and cache (which contains a virtualenv) and copy that around to other machines.

I know in you case you said you have local git server, but for anyone else who may be trying the same thing in the future, I'll point out that you don't strictly need that.   You can download the repo into a bundle file, and then use the "insteadOf" git configuration feature point your local bundle file instead of a live repo, with just a few steps:

    # Developer workstation (online)
    git clone https://github.com/Kintyre/ksconf.git
    ( cd ksconf; git bundle create /var/repo.cache/github/Kintyre/ksconf.git --all; ) 
    # Copy /var/repo.cache/github/Kintyre/ksconf.git to the same location on the offline machine
    
    # Offline workstation
    git config --global url."/var/repo.cache/git_mirror/github/".insteadOf https://github.com/

Now `git clone https://github.com/Kintyre/ksconf.git` will work from the bundle file rather than trying to open an outbound HTTPS connection to github.com.

**Comment by tiberiustribun** [comment]
Thanks for the exhausting answer. I got it working by using the proposed PIP_FIND_LINKS method. Problem was as you pointed out the OS supplied version of pip (Linux Mint 19 / Ubuntu 18.4) which was too old and needed to be upgraded. Which is of course caused problems with the OS managed Python enviroment. 
In hindsight I should have set up a dev environment in a VM or container.

After reading everything you pointed out I see that this is not really a ksconf issue but just the way the pre-commit folks decided to go. So issue closed for my part. Thanks again.

**Comment by lowell80** [comment]
I'm glad to hear that you got things working.   I'm less concerned about who's issue it is, and more interested in find a solution.  ;-)

Let me know if you hit other issues or have enhancement ideas.  Best of luck!
