### ISSUE TITLE
Sections without KV entries and a following line-break are incorrectly dropped

### ISSUE THREAD

**Issue by nebffa** [Kintyre/ksconf#77]
# The problem

Sections without KV entries that occur on consecutive lines without intermediate line-breaks do not get 'recognised', except for the first section.

## Environment

* Ksconf version:  0.7.8

## Details

For example, the Splunk db connect app contains this config in its `authorize.conf`

```
[capability::db_connect_create_connection]
[capability::db_connect_read_connection]
[capability::db_connect_update_connection]
[capability::db_connect_delete_connection]
```

Only the `capability::db_connect_create_connection` is recognised. The next 3 capabilities are dropped. This behaviour causes the db connect app to incorrectly function.

This occurs due to the code at https://github.com/Kintyre/ksconf/blob/master/ksconf/conf/parser.py#L121-L124 which only yields the entry if the `buf` is non-empty. When a line-break is present, the `buf` contains an `''` entry and is returned. Sections without that following empty line have an empty `buf` and are dropped. 

I'd contribute a fix but need to figure out with my company first I'm allowed.

**Comment by lowell80** [comment]
Ben, thanks for the bug report and provided detail.  This certainly is a problem, and frankly I'm a bit surprised I've not hit this before.  I think you're right about where the bug is.  I'm working on some unit tests now highlighting the broken behavior and will dig in further from there.

I suspect this has been previously missed because (1) empty stanzas are infrequent and/or meaningless for most `.conf` files, with `authorize.conf` being an exception, and (2) once a file has been normalized (opened and then saved) by ksconf, with something like `ksconf sort` for example), then stanzas always have a trailing blank line, which avoids this bug.

**Comment by lowell80** [comment]
Ben,

Give this a try when you get a chance.  If it all works as desired, I'll roll out an official release.  Changes in 651373552d53.

```
pip install kintyre-splunk-conf==0.7.9rc1
```

**Comment by nebffa** [comment]
@lowell80 that's the fix I'd committed in our internal fork (which works) - you can roll it out into an official release
